name: Ejecutar tests con Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🔧 Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm run install

      - name: 🧪 Ejecutar pruebas
        run: npm run test
